apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lexical-chicken-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lexical-chicken-nodejs 
  name: lexical-chicken-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lexical-chicken-nodejs 
